import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { Header, NavBar, RestaurantCard } from './components';
import { PrismaClient } from '@prisma/client';

const inter = Inter({ subsets: ['latin'] })

const prisma = new PrismaClient();

const fetchRestaurants = async() => {
 const restaurants = await prisma.restaurant.findMany();
 return restaurants; 
}

export default async function Home() {
  const restaurants = await fetchRestaurants();
  console.log(restaurants);
  
  return (
    <>
      <Head>
        <title>OpenTable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Header />
        <div className="py-3 px-36 mt-10 flex flex-wrap">
          <RestaurantCard />
        </div>
      </main>
    </>
  )
}
